- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    create_home: false
    state: present

- name: Download node_exporter tarball
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: "0644"

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Install node_exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: "0755"
    remote_src: true

- name: Create systemd unit for node_exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true


- name: Create Prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus.yml"
    owner: "{{ app_owner }}"
    group: "{{ app_owner }}"
    mode: "0644"

- name: Ensure Prometheus data dir exists
  file:
    path: "{{ prometheus_dir }}/data"
    state: directory
    owner: "{{ app_owner }}"
    group: "{{ app_owner }}"
    mode: "0755"

- name: Install Prometheus systemd unit
  template:
    src: prometheus.container.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"

- name: Ensure Grafana data dir exists
  file:
    path: "{{ grafana_dir }}/data"
    state: directory
    owner: "{{ app_owner }}"
    group: "{{ app_owner }}"
    mode: "0755"

- name: Install Grafana systemd unit
  template:
    src: grafana.container.service.j2
    dest: /etc/systemd/system/grafana.service
    mode: "0644"

- name: Ensure Prometheus data dir has the proper permissions
  file:
    path: "{{ prometheus_dir }}/data"
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0775"
    recurse: true

- name: Ensure Grafana data dir has the proper permissions
  file:
    path: "{{ grafana_dir }}/data"
    state: directory
    owner: "472"
    group: "472"
    mode: "0775"
    recurse: true


- name: Enable and start Prometheus and Grafana
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - prometheus
    - grafana
